"""Schemas for analysis endpoint."""

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


class AlertItem(BaseModel):
    """Single alert generated by analysis."""

    code: str = Field(..., examples=["tachycardia"])
    severity: Literal["low", "medium", "high"] = Field(..., examples=["high"])
    message: str = Field(..., examples=["Heart rate is above 120 bpm."])
    evidence: dict[str, Any] = Field(default_factory=dict)


class AnalysisResponse(BaseModel):
    """Response body for analysis endpoint."""

    patient_id: str
    generated_at: datetime
    window_hours: int
    alerts: list[AlertItem]
